CREATE TABLE IF NOT EXISTS investments (
  id INT UNSIGNED NOT NULL AUTO_INCREMENT,
  user_id INT NOT NULL,
  product_id INT UNSIGNED NOT NULL,
  amount DECIMAL(15,2) NOT NULL,
  percentage DECIMAL(5,2) NOT NULL,
  duration INT NOT NULL,
  daily_profit DECIMAL(15,2) NOT NULL,
  total_paid INT NOT NULL DEFAULT 0,
  total_returned DECIMAL(15,2) NOT NULL DEFAULT 0.00,
  last_return_at DATETIME NULL,
  next_return_at DATETIME NULL,
  order_id VARCHAR(191) NOT NULL UNIQUE,
  status ENUM('Pending','Running','Completed','Suspended','Cancelled') NOT NULL DEFAULT 'Pending',
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  INDEX idx_user_id (user_id),
  INDEX idx_product_id (product_id),
  INDEX idx_status (status),
  INDEX idx_next_return_at (next_return_at),
  CONSTRAINT fk_investments_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_investments_product FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE RESTRICT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;