-- Reset banks: hapus data lama, insert data baru dari listbank
--
-- Cara jalankan (dari folder BackEnd):
--   mysql -h 127.0.0.1 -u vlauser -p vla-db < migrations/reset_banks.sql
--
-- Atau login dulu lalu paste/source:
--   mysql -h 127.0.0.1 -u vlauser -p vla-db
--   source migrations/reset_banks.sql
--
-- PERHATIAN: Jika ada bank_accounts (rekening user), ID bank jadi berubah.
-- User harus pilih ulang bank di bank_accounts. Atau hapus dulu:
--   DELETE FROM bank_accounts;  (jika tidak perlu data rekening lama)

SET FOREIGN_KEY_CHECKS = 0;

DELETE FROM banks;
ALTER TABLE banks AUTO_INCREMENT = 1;

INSERT INTO banks (id, name, short_name, type, code, status) VALUES
(1, 'Dana', 'DANA', 'ewallet', 'DANA', 'Active'),
(2, 'GoPay', 'GOPAY', 'ewallet', 'GOPAY', 'Active'),
(3, 'OVO', 'OVO', 'ewallet', 'OVO', 'Active'),
(4, 'ShopeePay', 'SHOPEEPAY', 'ewallet', 'SHOPEEPAY', 'Active'),
(5, 'LinkAja', 'LINKAJA', 'ewallet', 'LINKAJA', 'Active'),
(6, 'Bank BRI', 'BRI', 'bank', '002', 'Active'),
(7, 'Bank Mandiri', 'MANDIRI', 'bank', '008', 'Active'),
(8, 'Bank BNI', 'BNI', 'bank', '009', 'Active'),
(9, 'Bank Danamon Indonesia', 'DANAMON', 'bank', '011', 'Active'),
(10, 'Bank Permata', 'PERMATA', 'bank', '013', 'Active'),
(11, 'Bank BCA', 'BCA', 'bank', '014', 'Active'),
(12, 'Bank Maybank Indonesia', 'MAYBANK', 'bank', '016', 'Active'),
(13, 'Bank Panin', 'PANIN', 'bank', '019', 'Active'),
(14, 'Bank CIMB Niaga', 'CIMB', 'bank', '022', 'Active'),
(15, 'Bank UOB Indonesia', 'UOB', 'bank', '023', 'Active'),
(16, 'Bank OCBC Indonesia', 'OCBC', 'bank', '028', 'Active'),
(17, 'Citibank, N.A', 'CITIBANK', 'bank', '031', 'Active'),
(18, 'JP. Morgan Chase Bank, N.A', 'JPM', 'bank', '032', 'Active'),
(19, 'Bank of America, N.A', 'BOA', 'bank', '033', 'Active'),
(20, 'China Construction Bank Indonesia', 'CCB', 'bank', '036', 'Active'),
(21, 'Bank Artha Graha Internasional', 'AGI', 'bank', '037', 'Active'),
(22, 'Bangkok Bank', 'BANGKOK', 'bank', '040', 'Active'),
(23, 'MUFG Bank, Ltd.', 'MUFG', 'bank', '042', 'Active'),
(24, 'Bank DBS Indonesia', 'DBS', 'bank', '046', 'Active'),
(25, 'Bank Resona Perdania', 'BRP', 'bank', '047', 'Active'),
(26, 'Bank Mizuho Indonesia', 'MIZUHO', 'bank', '048', 'Active'),
(27, 'Standard Chartered Bank', 'CHARTERED', 'bank', '050', 'Active'),
(28, 'Bank Capital Indonesia', 'CAPITAL', 'bank', '054', 'Active'),
(29, 'Bank BNP Paribas Indonesia', 'BNP', 'bank', '057', 'Active'),
(30, 'Bank ANZ Indonesia', 'ANZ', 'bank', '061', 'Active'),
(31, 'Deutsche Bank AG', 'DEUTSCHE', 'bank', '067', 'Active'),
(32, 'Bank of China', 'BOC', 'bank', '069', 'Active'),
(33, 'Bank Bumi Arta', 'ARTA', 'bank', '076', 'Active'),
(34, 'Bank HSBC Indonesia', 'HSBC', 'bank', '087', 'Active'),
(35, 'Bank J Trust Indonesia', 'JTRUST', 'bank', '095', 'Active'),
(36, 'Bank Mayapada', 'MAYAPADA', 'bank', '097', 'Active'),
(37, 'Bank BJB', 'BJB', 'bank', '110', 'Active'),
(38, 'Bank DKI', 'DKI', 'bank', '111', 'Active'),
(39, 'Bank BPD DIY', 'DIY', 'bank', '112', 'Active'),
(40, 'Bank Jateng', 'JATENG', 'bank', '113', 'Active'),
(41, 'Bank Jatim', 'JATIM', 'bank', '114', 'Active'),
(42, 'Bank Jambi', 'JAMBI', 'bank', '115', 'Active'),
(43, 'Bank Aceh Syariah', 'ACEHSYARIAH', 'bank', '116', 'Active'),
(44, 'Bank Sumut', 'SUMUT', 'bank', '117', 'Active'),
(45, 'Bank Nagari', 'NAGARI', 'bank', '118', 'Active'),
(46, 'Bank Riau Kepri Syariah', 'RIAUSYARIAH', 'bank', '119', 'Active'),
(47, 'Bank Sumsel Babel', 'SUMSEL', 'bank', '120', 'Active'),
(48, 'Bank Lampung', 'LAMPUNG', 'bank', '121', 'Active'),
(49, 'Bank Kalsel', 'KALSEL', 'bank', '122', 'Active'),
(50, 'Bank Kalbar', 'KALBAR', 'bank', '123', 'Active'),
(51, 'Bank Kaltimtara', 'KALTIM', 'bank', '124', 'Active'),
(52, 'Bank Kalteng', 'KALTENG', 'bank', '125', 'Active'),
(53, 'Bank Sulselbar', 'SULSELBAR', 'bank', '126', 'Active'),
(54, 'Bank SulutGo', 'SULUTGO', 'bank', '127', 'Active'),
(55, 'Bank NTB Syariah', 'NTBSYARIAH', 'bank', '128', 'Active'),
(56, 'Bank BPD Bali', 'BALI', 'bank', '129', 'Active'),
(57, 'Bank NTT', 'NTT', 'bank', '130', 'Active'),
(58, 'Bank Maluku Malut', 'MALUKU', 'bank', '131', 'Active'),
(59, 'Bank Papua', 'PAPUA', 'bank', '132', 'Active'),
(60, 'Bank Bengkulu', 'BENGKULU', 'bank', '133', 'Active'),
(61, 'Bank Sulteng', 'SULTENG', 'bank', '134', 'Active'),
(62, 'Bank Sultra', 'SULTRA', 'bank', '135', 'Active'),
(63, 'Bank Banten', 'BANTEN', 'bank', '137', 'Active'),
(64, 'Bank of India Indonesia', 'BOI', 'bank', '146', 'Active'),
(65, 'Bank Muamalat Indonesia', 'MUAMALAT', 'bank', '147', 'Active'),
(66, 'Bank Mestika Dharma', 'MESTIKA', 'bank', '151', 'Active'),
(67, 'Bank Shinhan Indonesia', 'SHINHAN', 'bank', '152', 'Active'),
(68, 'Bank Sinarmas', 'SINARMAS', 'bank', '153', 'Active'),
(69, 'Bank Maspion Indonesia', 'MASPION', 'bank', '157', 'Active'),
(70, 'Bank Ganesha', 'GANESHA', 'bank', '161', 'Active'),
(71, 'Bank ICBC Indonesia', 'ICBC', 'bank', '164', 'Active'),
(72, 'Bank QNB Indonesia', 'QNB', 'bank', '167', 'Active'),
(73, 'Bank BTN', 'BTN', 'bank', '200', 'Active'),
(74, 'Bank Woori Saudara', 'WOORI', 'bank', '212', 'Active'),
(75, 'Bank SMBC Indonesia (Jenius)', 'JENIUS', 'bank', '213', 'Active'),
(76, 'Bank BJB Syariah', 'BJBSYARIAH', 'bank', '425', 'Active'),
(77, 'Bank Mega', 'MEGA', 'bank', '426', 'Active'),
(78, 'Bank KB Bukopin', 'BUKOPIN', 'bank', '441', 'Active'),
(79, 'Bank Syariah Indonesia (BSI)', 'BSI', 'bank', '451', 'Active'),
(80, 'Krom Bank Indonesia', 'KROM', 'bank', '459', 'Active'),
(81, 'Bank Jasa Jakarta', 'BJJ', 'bank', '472', 'Active'),
(82, 'Bank Hana (Line Bank)', 'LINE', 'bank', '484', 'Active'),
(83, 'Bank MNC Internasional', 'MNC', 'bank', '485', 'Active'),
(84, 'Bank Neo Commerce', 'NEO', 'bank', '490', 'Active'),
(85, 'Bank Raya Indonesia', 'RAYA', 'bank', '494', 'Active'),
(86, 'Bank SBI Indonesia', 'SBI', 'bank', '498', 'Active'),
(87, 'Bank Digital BCA (blu)', 'BLU', 'bank', '501', 'Active'),
(88, 'Bank National Nobu', 'NOBU', 'bank', '503', 'Active'),
(89, 'Bank Mega Syariah', 'MEGASYARIAH', 'bank', '506', 'Active'),
(90, 'Bank Ina Perdana', 'INA', 'bank', '513', 'Active'),
(91, 'Bank Panin Dubai Syariah', 'PANINSYARIAH', 'bank', '517', 'Active'),
(92, 'Prima Master Bank', 'PRIMA', 'bank', '520', 'Active'),
(93, 'Bank KB Bukopin Syariah', 'BUKOPINSYARIAH', 'bank', '521', 'Active'),
(94, 'Bank Sahabat Sampoerna', 'SAMPOERNA', 'bank', '523', 'Active'),
(95, 'Bank Oke Indonesia', 'OKE', 'bank', '526', 'Active'),
(96, 'Bank Amar Indonesia', 'AMAR', 'bank', '531', 'Active'),
(97, 'SeaBank Indonesia', 'SEABANK', 'bank', '535', 'Active'),
(98, 'Bank BCA Syariah', 'BCASYARIAH', 'bank', '536', 'Active'),
(99, 'Bank Jago', 'JAGO', 'bank', '542', 'Active'),
(100, 'Bank BTPN Syariah', 'BTPNSYARIAH', 'bank', '547', 'Active'),
(101, 'Bank Multi Arta Sentosa', 'MAS', 'bank', '548', 'Active'),
(102, 'Bank Hibank Indonesia', 'HIBANK', 'bank', '553', 'Active'),
(103, 'Bank Index Selindo', 'INDEX SELINDO', 'bank', '555', 'Active'),
(104, 'Super Bank Indonesia', 'SUPERBANK', 'bank', '562', 'Active'),
(105, 'Bank Mandiri Taspen', 'MANDIRITASPEN', 'bank', '564', 'Active'),
(106, 'Bank Victoria International', 'VICTORIA', 'bank', '566', 'Active'),
(107, 'Allo Bank Indonesia', 'ALLO', 'bank', '567', 'Active'),
(108, 'Bank IBK Indonesia', 'IBK', 'bank', '945', 'Active'),
(109, 'Bank Aladin Syariah', 'ALADIN', 'bank', '947', 'Active'),
(110, 'Bank CTBC Indonesia', 'CTBC', 'bank', '949', 'Active'),
(111, 'Bank Commonwealth', 'COMMONWEALTH', 'bank', '950', 'Active');

SET FOREIGN_KEY_CHECKS = 1;
